# Generated by Django 5.1 on 2024-08-24 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chamado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resumo', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=100)),
                ('solicitante', models.CharField(max_length=100)),
                ('data_criacao', models.CharField(max_length=100)),
                ('data_atualizacao', models.CharField(max_length=100)),
                ('responsavel', models.CharField(max_length=100)),
                ('link', models.URLField()),
            ],
        ),
    ]
